{
 "title": "7. Golden Signals (SRE Standard)",
 "tags": [ "sre" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffic (Request Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Global RPS"
    }
   ]
  },
  {
   "title": "Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le))",
     "legendFormat": "Global P95 Latency"
    }
   ]
  },
  {
   "title": "Errors (Total Status 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "Global Errors"
    }
   ]
  },
  {
   "title": "Saturation (Node CPU Load)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}