{
 "title": "2. Microservices Performance",
 "tags": [ "apps" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Latency P95 (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100",
     "legendFormat": "5xx Errors %"
    }
   ]
  },
  {
   "title": "Service Availability (Up)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "avg(up) by (job)", "legendFormat": "{{job}}" }
   ]
  }
 ]
}