{
 "title": "8. PostgreSQL Overview",
 "tags": [
  "postgres",
  "db"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "PostgreSQL Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[5m])) by (datname)",
     "legendFormat": "Commits {{datname}}"
    }
   ]
  },
  {
   "title": "Database Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blks_hit[5m])) / (sum(rate(pg_stat_database_blks_hit[5m])) + sum(rate(pg_stat_database_blks_read[5m]))) * 100",
     "legendFormat": "Hit Ratio %"
    }
   ]
  }
 ]
}